mkPost
Ucekay/music_socialmedia pull request #11
Opened 2024-05-16 08:10 UTC by kaeru61

2024-05-16 12:17 UTC, Ucekay requested changes
変更した方が良い点をコメントしているので確認して適宜修正してください。
可能であれば、expo 51にアップデートして問題がないか確認してください。

2024-05-16 12:17 UTC, Ucekay commented on src/app/(tabs)/(post)/index.tsx
`FlashList`のPropsには` estimatedItemSize`を追加してください。
また、`Animated.View`である必要はありません。

2024-05-16 12:17 UTC, Ucekay commented on src/app/(tabs)/(post)/index.tsx
`estimatedItemSize`を明示することによってレンダリングの最適化が行われ、パフォーマンスに優位です。
`PostCard`の高さの平均値や最大値を設定してください。

2024-05-16 12:17 UTC, Ucekay commented on src/components/Icon/AntDesign.tsx
コンポーネント名がわかりにくいのでわかりやすいものに変更してください。

2024-05-16 12:17 UTC, Ucekay commented on src/components/PostCard.tsx
music urlやimage urlが存在するかどうかでそれぞれの事象に対して個別のレンダリングを行っているが、コードの繰り返しが煩雑なので、一回のreturnで
`post.musicUrl && ( <MusicBarOfPost />)`
などのようにしてpost.musicUrlが存在する時だけ`<MusicBarOfPost />`をレンダリングする方が良い。

2024-05-16 12:17 UTC, Ucekay commented on src/components/UserTagPD.tsx
`Tag`という名称は誤解を生む可能性があるので変更してください。
できれば`PD`も理解に時間がかかるので変更してください。

2024-05-16 12:17 UTC, Ucekay commented on src/types.ts
`PostDataTypeD`と`PostDataType`の違いが一見するとわからないので、より何のための型付けなのかがわかるようにしてください。

2024-05-16 16:26 UTC, Ucekay requested changes

2024-05-16 16:26 UTC, Ucekay commented on src/app/(tabs)/(post)/[id].tsx
if (post.imageUrl)の中でレンダリングしないようにすれば繰り返しをさらに減らせる。
if文の中ではimage sizeを設定するだけにしてください。

2024-05-16 16:34 UTC, Ucekay requested changes

2024-05-16 16:34 UTC, Ucekay commented on src/app/(tabs)/(post)/[id].tsx
`react-native`からの`Image`を`Image.getSize()`関数の使用のためにインポートしていますが、 `expo-image`からの`Image`の方がパフォーマンス優位なので、`Image`コンポーネントは`expo-image`からインポートしたものを使用してください。
`Image.getSize()`を使用するためには、`react-native`からの`Image`を
`import Image as RNImage from 'react-native'`
のように別の名称でインポートして
`RNImage.getSize()`
を使用すると良いです。

2024-05-17 02:55 UTC, kaeru61 commented on src/app/(tabs)/(post)/[id].tsx
if文の中でima;gesizeを取得しているため、同様のif文内でないとerrorを吐きます。

2024-05-17 03:03 UTC, kaeru61 commented on src/types.ts
必要ないので消しました

2024-05-17 03:37 UTC, Ucekay approved these changes

2024-05-17 03:37 UTC, Ucekay commented on src/app/(tabs)/(post)/[id].tsx
todo : 繰り返しを解消

2024-05-17 03:37 UTC, merged