app profileのユーザー取得とff一覧取得、updateを実装しました
Ucekay/music_socialmedia pull request #45
Opened 2024-10-19 16:37 UTC by kaeru61

2024-10-19 16:47 UTC, Ucekay commented
`.vscode/settings.json`は`.vscode/settings.json.template`にして以下の内容を記載して下さい。
```
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "editor.indentSize": "tabSize",
  "editor.defaultFormatter": "biomejs.biome",
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "editor.codeActionsOnSave": {
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit",
    "source.addMissingImports": "explicit",
    "source.fixAll.eslint": "explicit"
  }
}
```
全員自分の環境のvscodeの`settings.json'に`.vscode/settings.json.template`の内容を反映させるようにしましょう。

2024-10-19 16:53 UTC, Ucekay requested changes

2024-10-19 16:53 UTC, Ucekay commented on src/components/UserProfileTop.tsx
> +              key={index}
`key`に`index`をそのまま指定するのは避けて修正して下さい

2024-10-19 16:53 UTC, Ucekay commented on src/components/UserProfileTopOfLoginUser.tsx
> +              key={index}
`key`に`index`をそのまま使用するのは避けて下さい

2024-10-19 17:11 UTC, Ucekay commented on Makefile
`Makefile`を使ってもこの程度のスクリプトなら、`package.json`の`scripts`に定義した方が一箇所にまとめられて良いのではないですか？

2024-10-20 08:43 UTC, kaeru61 commented on Makefile
今後増える可能性があるのとmakeの手グセがついてるってのと

2024-10-20 08:48 UTC, kaeru61 commented
formatter秋雨生ずみです

2024-10-21 02:27 UTC, Ucekay commented on Makefile
なら`.gitignore`に追加して

2024-10-21 02:39 UTC, Ucekay commented
linterのエラーも`bunx biome check --write`を実行したら修正されるはずなので修正しておいて下さい

2024-10-21 05:45 UTC, merged